In [ ]:
# VIDEO 3 NUMPY
import numpy as np #Biblioteca Numpy 
np.array([10,20,24,5,15,50])

array([10, 20, 24,  5, 15, 50])

In [ ]:
a= np.array([10,30,20,4,30,51,7,2,4,40,100]) #Coloca el arreglo en una variable
a[4]

30

In [ ]:
a[3:] #Indica que a partir del índice 3 muestre el resto del arreglo

array([  4,  30,  51,   7,   2,   4,  40, 100])

In [ ]:
a[3:7] #Imprime de la posición 3 hasta la 7

array([ 4, 30, 51,  7])

In [ ]:
a[1::4] #Imprime la primer posición indicada (1) y cada cuantas posiciones (4)

array([30, 51, 40])

In [ ]:
np.zeros(5) #Crea 5 elementos con el valor de cero

array([0., 0., 0., 0., 0.])

In [ ]:
ones= np.ones((4,5))#Crea un arreglo de dos dimensiones con 4 filas y 5 columnas
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
type(ones)#Indica qué tipo de arreglo es 

numpy.ndarray

In [ ]:
type(ones[0][3]) #Me indica qué tipo de dato es un valor indicando en el primer corchete la fila y en el segundo, la posición

numpy.float64

In [ ]:
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [ ]:
b=np.array([['x','y','z'],['a','c','e']]) #Imprime un arreglo de dos dimensiones y dice el tipo
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [ ]:
b.ndim #Indica cuántas dimensiones tiene b 

2

In [ ]:
c=[12,4,10,40,2] #Para ordenar
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [ ]:
cabeceras=[('nombre', 'S10'), ('edad', int)] #Ordena por edad 
datos= [('Juan', 10), ('Maria',70), ('Javier', 42), ('Samuel', 15)]
usuarios= np.array(datos, dtype=cabeceras)
np.sort(usuarios, order='edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [ ]:
np.arange(25) #Pide 25 elementos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.arange(5,30)#Muestra los elementos del 5 al 30 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(5,50,5)#Indica el valor inicial, el final y de cuánto en cuánto se incrementa

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.full((3,5), 10) #Indica que debe tener 3 filas, 5 columnas y un único valor que es 10

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
np.diag([0,3,9,10]) #Indica que queremos una diagonal de este arreglo bidimensional 

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

In [ ]:
#RETO VIDEO 3
import numpy as np

etiquetas= [('edad', int), ('nombre', 'S10'), ('país', 'S10')]
datos= [(12, 'Clara', 'Argentina'), (25, 'Hernan', 'Chile'), (30, 'Joan', 'Francia'), (46, 'Marisa', 'Paraguay')]
usuarios= np.array(datos, dtype=etiquetas)
np.sort(usuarios, order='nombre')

array([(12, b'Clara', b'Argentina'), (25, b'Hernan', b'Chile'),
       (30, b'Joan', b'Francia'), (46, b'Marisa', b'Paraguay')],
      dtype=[('edad', '<i8'), ('nombre', 'S10'), ('país', 'S10')])

In [ ]:
#VIDEO 4 PANDAS
import pandas as pd #Primero importarla


In [ ]:
#SERIES:
series=pd.Series([5,10,15,20,25]) 

In [ ]:
print(series)

0     5
1    10
2    15
3    20
4    25
dtype: int64


In [ ]:
type(series) #Indica de qué tipo es

pandas.core.series.Series

In [ ]:
series[3] #Muestra el valor alojado en ese indice/posición

20

In [ ]:
cad=pd.Series(['p','l','a','t','z','i']) #Muestra cada una de las letras
cad

0    p
1    l
2    a
3    t
4    z
5    i
dtype: object

In [ ]:
#DATAFRAMES:
list=['Hola','mundo','robótico'] #Crea un DataFrame
df= pd.DataFrame(list)
print(df)

          0
0      Hola
1     mundo
2  robótico


In [ ]:
data={'Nombre':['Juan', 'Ana', 'José', 'Arturo'], #Crea una estructura como una tabla de Excel, un dataframe con llave y dato
      'Edad': [25,18,23,27],
      'País': ['MX', 'CO', 'BR', 'MX']}
df=pd.DataFrame (data)
df


Nombre  Edad País
0    Juan    25   MX
1     Ana    18   CO
2    José    23   BR
3  Arturo    27   MX

In [ ]:
print(df[['Nombre', 'País']]) #Para imprimir columnas en particular

   Nombre País
0    Juan   MX
1     Ana   CO
2    José   BR
3  Arturo   MX
